context:
  name: "granular"
  version: "0.23.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 4d5d4b7d5cc5796d4a8903615db5467013533b0b368ae7af639f8f1f28185ee1

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - cloudpickle
    - msgpack-python
    - numpy

tests:
  - python:
      imports:
        - granular
      python_version: ${{ python_min }}.*


about:
  homepage: http://github.com/danijar/granular
  summary: Fast format for datasets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noahjutz
